spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  data:
    redis:
      host: 127.0.0.1
      port: 6379

mybatis:
  mapper-locations: classpath:cwchoiit.board.mappers/*.xml

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false

aws:
  access-key: <your IAM User access key>
  secret-key: <your IAM User secret key>
  region: ap-northeast-2
  sns:
    default-topic: <your sns topic arn>
