spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/board
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root

mybatis:
  mapper-locations: classpath:cwchoiit.board.mappers/*.xml
